ccflags-y += -I$(src) -I$(src)/kmod \
    -isystem $(shell $(CC) -print-file-name=include) \
    -Wno-error=return-type -Wno-declaration-after-statement \
    -Wframe-larger-than=2048 -Wno-implicit-fallthrough \
    -msse4.2 -mavx2 \
    -mavx512f -mavx512cd -mavx512bw -mavx512vl -mavx512vnni \
    -std=gnu11

#    -mavx512vbmi -mavx512vbmi2 -mavx512vnni \
# flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities


obj-m := xdp_rex.o

xdp_rex-y :=                 \
    kmod/rex.o               \
    alloc.o                  \
    scratch.o                \
    runtime.o                \
    database.o               \
    hs_version.o             \
    stream_compress.o        \
    fdr/fdr.o                \
    fdr/teddy_avx2.o         \
    fdr/teddy.o              \
    hwlm/hwlm.o              \
    hwlm/noodle_engine.o     \
    nfa/accel.o              \
    nfa/castle.o             \
    nfa/gough.o              \
    nfa/lbr.o                \
    nfa/limex_64.o           \
    nfa/limex_accel.o        \
    nfa/limex_native.o       \
    nfa/limex_simd128.o      \
    nfa/limex_simd256.o      \
    nfa/limex_simd384.o      \
    nfa/limex_simd512.o      \
    nfa/mcclellan.o          \
    nfa/mcsheng.o            \
    nfa/mcsheng_data.o       \
    nfa/mpv.o                \
    nfa/nfa_api_dispatch.o   \
    nfa/repeat.o             \
    nfa/sheng.o              \
    nfa/shufti.o             \
    nfa/tamarama.o           \
    nfa/truffle.o            \
    rose/block.o             \
    rose/catchup.o           \
    rose/init.o              \
    rose/match.o             \
    rose/program_runtime.o   \
    rose/stream.o            \
    som/som_runtime.o        \
    som/som_stream.o         \
    util/cpuid_flags.o       \
    util/masked_move.o       \
    util/multibit.o          \
    util/simd_utils.o        \
    util/state_compress.o    \
#
